spring.application.name=PizzaApp
spring.profiles.active=local  
# 👈 Define active profile here (or use env variables)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
