spring.application.name=PizzaApp

server.port=8080


<<<<<<< HEAD
#server.servlet.session.cookie.same-site=strict
=======
server.servlet.session.cookie.same-site=strict
>>>>>>> 6705f8e (d)



# MySQL Database Configuration
spring.datasource.url={RENDER_DB_URL}
spring.datasource.username={DB_USER}
spring.datasource.password={DATABASE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.maximum-pool-size=10

# Debugging settings
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG  